### ISSUE TITLE
Missing guide to setup local environment and contribution guidelines

### ISSUE THREAD

**Issue by m-naeem66622** [najmiter/darkcircles#1]
There must be a README.md file for the user to setup the local environment and make it work.
Moreover, contributing guidelines also missing in this repo and License file.

**Comment by m-naeem66622** [comment]
Attempting to solve the issue #1

**Comment by najmiter** [comment]
readme was already created locally, i just hadn't pushed yet. but thanks for the star and the reminder ❤️ 
and everything here is licensed MIT unless specified otherwise 😄

**Comment by m-naeem66622** [comment]
Adding more details in readme file and setting up LICENSE file with copyright and name of the owner
Fixed issue in #2 
> Note: Replace the changes mentioned in Expected Changes section of Pull Requst note
